### ISSUE TITLE
Support running on non-org account (flat org)

### ISSUE THREAD

**Issue by gfrid** [aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#20]
Allow to run the migrator in non-org account (member account) in flat organization where there is no payer account as a operational account but rather a member account that has StackSet and access to all other member accounts by assume-role.
```
2023-11-07 10:15:11,745 - INFO - Running with boto client region = aws-global
2023-11-07 10:15:13,242 - ERROR - Script being run by a member account of AWS organization
2023-11-07 10:15:13,243 - ERROR - Failed calling Organization DescribeOrganization API
Traceback (most recent call last):
  File "C:\GitHub\aws-policy-migrator\policy_migration_scripts\scripts\identify_affected_policies.py", line 575, in <module>
    main()
  File "C:\GitHub\aws-policy-migrator\policy_migration_scripts\scripts\identify_affected_policies.py", line 488, in main
    validate_if_being_run_by_payer_account(org_client, caller_account)
  File "C:\GitHub\aws-policy-migrator\policy_migration_scripts\utils\validation.py", line 65, in validate_if_being_run_by_payer_account
    raise err
  File "C:\GitHub\aws-policy-migrator\policy_migration_scripts\utils\validation.py", line 55, in validate_if_being_run_by_payer_account
    raise ValidationException("Script can only be run by management account of an AWS Organization")
policy_migration_scripts.utils.model.ValidationException: Script can only be run by management account of an AWS Organization
```

**Comment by Gagan-Nagaraju** [comment]
Hey @gfrid, these scripts are meant to be run by the management account of organization and not a member account. Can you please provide some context on your Org setup, what kind of account you are using to run the script and why you are unable to run the scripts using the management account?
